const products = [{
        id: 0,
        src: ["Images/Products/1.jpg"],
        Name: "Relaxed Fit Hoodie",
        price: 649,
        status: "top",
        gender: "male",
    },
    {
        id: 1,
        src: ["Images/Products/2.jpg"],
        Name: "Relaxed Fit Hoodie",
        price: 649,
        status: "top",
        gender: "male",
    },
    {
        id: 2,
        src: ["Images/Products/3.jpg"],
        Name: "Relaxed Fit Hoodie",
        price: 649,
        status: "top",
        gender: "male",
    },
    {
        id: 3,
        src: ["Images/Products/4.jpg"],
        Name: "Relaxed Fit Hoodie",
        price: 649,
        status: "top",
        gender: "male",
    },
    {
        id: 4,
        src: ["Images/Products/POS/1.png"],
        Name: "Relaxed Fit Hoodie",
        price: 649,
        status: "sale",
        gender: "male",
    },
    {
        id: 5,
        src: ["Images/Products/POS/5.png"],
        Name: "Relaxed Fit Hoodie",
        price: 649,
        status: "sale",
        gender: "male",
    },
    {
        id: 6,
        src: ["Images/Products/POS/2.png"],
        Name: "Relaxed Fit Hoodie",
        price: 649,
        status: "sale",
        gender: "male",
    },
    {
        id: 7,
        src: ["Images/Products/POS/3.png"],
        Name: "Relaxed Fit Hoodie",
        price: 649,
        status: "sale",
        gender: "male",
    },
    {
        id: 8,
        src: ["Images/Products/POS/4.png"],
        Name: "Relaxed Fit Hoodie",
        price: 649,
        status: "sale",
        gender: "male",
    },
    {
        id: 9,
        src: ["Images/black outfits/black1.png"],
        Name: "Relaxed Fit Hoodie",
        price: 649,
        status: "top",
        gender: "female",
        color: "black",
    },
    {
        id: 10,
        src: ["Images/black outfits/black2.png"],
        Name: "Relaxed Fit Hoodie",
        price: 649,
        status: "top",
        gender: "female",
        color: "black",
    },
    {
        id: 11,
        src: ["Images/black outfits/black3.png"],
        Name: "Relaxed Fit Hoodie",
        price: 649,
        status: "top",
        gender: "male",
        color: "black",
    },
    {
        id: 12,
        src: ["Images/black outfits/black4.png"],
        Name: "Relaxed Fit Hoodie",
        price: 649,
        status: "top",
        gender: "male",
        color: "black",
    },
    {
        id: 13,
        src: ["Images/black outfits/black5.png"],
        Name: "Relaxed Fit Hoodie",
        price: 649,
        status: "sale",
        gender: "female",
        color: "black",
    },
    {
        id: 14,
        src: ["Images/black outfits/black6.png"],
        Name: "Relaxed Fit Hoodie",
        price: 649,
        status: "sale",
        gender: "female",
        color: "black",
    },
    {
        id: 15,
        src: ["Images/black outfits/black7.png"],
        Name: "Relaxed Fit Hoodie",
        price: 649,
        status: "sale",
        gender: "male",
        color: "black",
    },
    {
        id: 16,
        src: ["Images/black outfits/black8.png"],
        Name: "Relaxed Fit Hoodie",
        price: 649,
        status: "sale",
        gender: "female",
        color: "black",
    },
    {
        id: 17,
        src: ["Images/White/white1.jpg"],
        Name: "Relaxed Fit Hoodie",
        price: 649,
        status: "top",
        gender: "female",
        color: "White",
    },
    {
        id: 18,
        src: ["Images/White/white2.png"],
        Name: "Relaxed Fit Hoodie",
        price: 649,
        status: "top",
        gender: "male",
        color: "White",
    },
    {
        id: 19,
        src: ["Images/White/white3.png"],
        Name: "Relaxed Fit Hoodie",
        price: 649,
        status: "top",
        gender: "male",
        color: "White",
    },
    {
        id: 20,
        src: ["Images/White/white4.png"],
        Name: "Relaxed Fit Hoodie",
        price: 649,
        status: "top",
        gender: "male",
        color: "White",
    },
    {
        id: 21,
        src: ["Images/White/white5.png"],
        Name: "Relaxed Fit Hoodie",
        price: 649,
        status: "sale",
        gender: "male",
        color: "White",
    },
    {
        id: 22,
        src: ["Images/White/white6.png"],
        Name: "Relaxed Fit Hoodie",
        price: 649,
        status: "sale",
        gender: "male",
        color: "White",
    },
];
export default products;